# Generated by Django 4.0 on 2021-12-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
