# Generated by Django 4.0 on 2021-12-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profil',
        ),
    ]
