# Generated by Django 4.0 on 2021-12-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profil_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='User',
        ),
    ]
