# Generated by Django 4.0 on 2021-12-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_profil_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
